// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjdxqerqcedkrjiuddyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZHhxZXJxY2Vka3JqaXVkZHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTQ5NDksImV4cCI6MjA2NDA3MDk0OX0.fZvJkzYYDiBnMpwSiCN58-JnSRLRozg7mV3jNPmx-5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);